all: a b c

a: p4a.exe 

p4a.exe: p4a.obj
    tlink /v p4a

p4a.obj: p4a.asm
    tasm /zi p4a


b: p4b.exe 

p4b.exe: p4b.obj
    tlink /v p4b

p4b.obj: p4b.asm
    tasm /zi p4b


c: p4c.exe 

p4c.exe: p4c.obj
    tlink /v p4c

p4c.obj: p4c.asm
    tasm /zi p4c

clean: 
	del *.EXE 
	del *.MAP 
	del *.OBJ
