all: a b c

a: p4a.com 

p4a.com: p4a.obj
    tlink /t p4a

p4a.obj: p4a.asm
	tasm /zi /m p4a

p4a.exe: p4a.obj
    tlink /t p4b

b: p4b.exe 

p4b.exe: p4b.obj
    tlink /v p4b

p4b.obj: p4b.asm
	tasm /zi /m p4b


c: p4c.exe 

p4c.exe: p4c.obj
    tlink /v p4c

p4c.obj: p4c.asm
	tasm /zi /m p4c

clean:
	del *.EXE
	del *.COM
	del *.OBJ
	del *.MAP